name: Create Release and Update Repository

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    uses: Lunatory/DalamudRepo/.github/workflows/reusable_create_release.yml@master
    with:
      internal_name: BetterPartyFinder
      solution_name: BetterPartyFinder
      build_configuration: Release
      personal_plugin_repo: Lunatory/BetterPartyFinder
      personal_plugin_repo_branch: main
    secrets: inherit