name: Create Release and Update Repository

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    uses: Lunatory/DalamudRepo/.github/workflows/reusable_create_release.yml@master
    with:
      internal_name: BetterPartyFinderPlus
      solution_name: BetterPartyFinderPlus
      build_configuration: Release
      personal_plugin_repo: Lunatory/BetterPartyFinderPlus
      personal_plugin_repo_branch: master
    secrets: inherit